/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V18.4.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models


type N32Purpose string

// List of N32Purpose
const (
        N32Purpose_ROAMING N32Purpose = "ROAMING"
        N32Purpose_INTER_PLMN_MOBILITY N32Purpose = "INTER_PLMN_MOBILITY"
        N32Purpose_SMS_INTERCONNECT N32Purpose = "SMS_INTERCONNECT"
        N32Purpose_ROAMING_TEST N32Purpose = "ROAMING_TEST"
        N32Purpose_INTER_PLMN_MOBILITY_TEST N32Purpose = "INTER_PLMN_MOBILITY_TEST"
        N32Purpose_SMS_INTERCONNECT_TEST N32Purpose = "SMS_INTERCONNECT_TEST"
        N32Purpose_SNPN_INTERCONNECT N32Purpose = "SNPN_INTERCONNECT"
        N32Purpose_SNPN_INTERCONNECT_TEST N32Purpose = "SNPN_INTERCONNECT_TEST"
        N32Purpose_DISASTER_ROAMING N32Purpose = "DISASTER_ROAMING"
        N32Purpose_DISASTER_ROAMING_TEST N32Purpose = "DISASTER_ROAMING_TEST"
)


