/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models


type SupportedGadShapes string

// List of SupportedGADShapes
const (
        SupportedGadShapes_POINT SupportedGadShapes = "POINT"
        SupportedGadShapes_POINT_UNCERTAINTY_CIRCLE SupportedGadShapes = "POINT_UNCERTAINTY_CIRCLE"
        SupportedGadShapes_POINT_UNCERTAINTY_ELLIPSE SupportedGadShapes = "POINT_UNCERTAINTY_ELLIPSE"
        SupportedGadShapes_POLYGON SupportedGadShapes = "POLYGON"
        SupportedGadShapes_POINT_ALTITUDE SupportedGadShapes = "POINT_ALTITUDE"
        SupportedGadShapes_POINT_ALTITUDE_UNCERTAINTY SupportedGadShapes = "POINT_ALTITUDE_UNCERTAINTY"
        SupportedGadShapes_ELLIPSOID_ARC SupportedGadShapes = "ELLIPSOID_ARC"
        SupportedGadShapes_LOCAL_2_D_POINT_UNCERTAINTY_ELLIPSE SupportedGadShapes = "LOCAL_2D_POINT_UNCERTAINTY_ELLIPSE"
        SupportedGadShapes_LOCAL_3_D_POINT_UNCERTAINTY_ELLIPSOID SupportedGadShapes = "LOCAL_3D_POINT_UNCERTAINTY_ELLIPSOID"
)


