/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Information of a P-CSCF NF Instance
type PcscfInfo struct {
	AccessType []*AccessType `json:"accessType,omitempty" yaml:"accessType" bson:"accessType"`
	DnnList []*string `json:"dnnList,omitempty" yaml:"dnnList" bson:"dnnList"`
	// Fully Qualified Domain Name
	GmFqdn string `json:"gmFqdn,omitempty" yaml:"gmFqdn" bson:"gmFqdn"`
	GmIpv4Addresses []*string `json:"gmIpv4Addresses,omitempty" yaml:"gmIpv4Addresses" bson:"gmIpv4Addresses"`
	GmIpv6Addresses []*string `json:"gmIpv6Addresses,omitempty" yaml:"gmIpv6Addresses" bson:"gmIpv6Addresses"`
	// Fully Qualified Domain Name
	MwFqdn string `json:"mwFqdn,omitempty" yaml:"mwFqdn" bson:"mwFqdn"`
	MwIpv4Addresses []*string `json:"mwIpv4Addresses,omitempty" yaml:"mwIpv4Addresses" bson:"mwIpv4Addresses"`
	MwIpv6Addresses []*string `json:"mwIpv6Addresses,omitempty" yaml:"mwIpv6Addresses" bson:"mwIpv6Addresses"`
	ServedIpv4AddressRanges []*Ipv4AddressRange `json:"servedIpv4AddressRanges,omitempty" yaml:"servedIpv4AddressRanges" bson:"servedIpv4AddressRanges"`
	ServedIpv6PrefixRanges []*Ipv6PrefixRange `json:"servedIpv6PrefixRanges,omitempty" yaml:"servedIpv6PrefixRanges" bson:"servedIpv6PrefixRanges"`
}
