/*
 * Nudsf_DataRepository
 *
 * Nudsf Data Repository Service.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.598 UDSF Services, V17.6.0.
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.598/
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Error returned in the access token response message
type AccessTokenErr struct {
	Error string `json:"error" yaml:"error" bson:"error"`
	ErrorDescription string `json:"error_description,omitempty" yaml:"error_description" bson:"error_description"`
	ErrorUri string `json:"error_uri,omitempty" yaml:"error_uri" bson:"error_uri"`
}
