/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models


type N1MessageClass string

// List of N1MessageClass
const (
        N1MessageClass__5_GMM N1MessageClass = "5GMM"
        N1MessageClass_SM N1MessageClass = "SM"
        N1MessageClass_LPP N1MessageClass = "LPP"
        N1MessageClass_SMS N1MessageClass = "SMS"
        N1MessageClass_UPDP N1MessageClass = "UPDP"
        N1MessageClass_LCS N1MessageClass = "LCS"
)


