/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Information of an NEF NF Instance
type NefInfo struct {
	// Identity of the NEF
	NefId string `json:"nefId,omitempty" yaml:"nefId" bson:"nefId"`
	PfdData *PfdData `json:"pfdData,omitempty" yaml:"pfdData" bson:"pfdData"`
	AfEeData *AfEventExposureData `json:"afEeData,omitempty" yaml:"afEeData" bson:"afEeData"`
	GpsiRanges []*IdentityRange `json:"gpsiRanges,omitempty" yaml:"gpsiRanges" bson:"gpsiRanges"`
	ExternalGroupIdentifiersRanges []*IdentityRange `json:"externalGroupIdentifiersRanges,omitempty" yaml:"externalGroupIdentifiersRanges" bson:"externalGroupIdentifiersRanges"`
	ServedFqdnList []*string `json:"servedFqdnList,omitempty" yaml:"servedFqdnList" bson:"servedFqdnList"`
	TaiList []*Tai `json:"taiList,omitempty" yaml:"taiList" bson:"taiList"`
	TaiRangeList []*TaiRange `json:"taiRangeList,omitempty" yaml:"taiRangeList" bson:"taiRangeList"`
	DnaiList []*string `json:"dnaiList,omitempty" yaml:"dnaiList" bson:"dnaiList"`
	UnTrustAfInfoList []*UnTrustAfInfo `json:"unTrustAfInfoList,omitempty" yaml:"unTrustAfInfoList" bson:"unTrustAfInfoList"`
	UasNfFunctionalityInd bool `json:"uasNfFunctionalityInd,omitempty" yaml:"uasNfFunctionalityInd" bson:"uasNfFunctionalityInd"`
}
