/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Information of an LMF NF Instance
type LmfInfo struct {
	ServingClientTypes []*ExternalClientType `json:"servingClientTypes,omitempty" yaml:"servingClientTypes" bson:"servingClientTypes"`
	// LMF identification.
	LmfId string `json:"lmfId,omitempty" yaml:"lmfId" bson:"lmfId"`
	ServingAccessTypes []*AccessType `json:"servingAccessTypes,omitempty" yaml:"servingAccessTypes" bson:"servingAccessTypes"`
	ServingAnNodeTypes []*AnNodeType `json:"servingAnNodeTypes,omitempty" yaml:"servingAnNodeTypes" bson:"servingAnNodeTypes"`
	ServingRatTypes []*RatType `json:"servingRatTypes,omitempty" yaml:"servingRatTypes" bson:"servingRatTypes"`
	TaiList []*Tai `json:"taiList,omitempty" yaml:"taiList" bson:"taiList"`
	TaiRangeList []*TaiRange `json:"taiRangeList,omitempty" yaml:"taiRangeList" bson:"taiRangeList"`
	SupportedGADShapes []*SupportedGadShapes `json:"supportedGADShapes,omitempty" yaml:"supportedGADShapes" bson:"supportedGADShapes"`
}
