/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Information of an SCP Instance
type ScpInfo struct {
	// A map (list of key-value pairs) where the key of the map shall be the string identifying an SCP domain 
	ScpDomainInfoList map[string]*ScpDomainInfo `json:"scpDomainInfoList,omitempty" yaml:"scpDomainInfoList" bson:"scpDomainInfoList"`
	ScpPrefix string `json:"scpPrefix,omitempty" yaml:"scpPrefix" bson:"scpPrefix"`
	// Port numbers for HTTP and HTTPS. The key of the map shall be \"http\" or \"https\". 
	ScpPorts map[string]*int32 `json:"scpPorts,omitempty" yaml:"scpPorts" bson:"scpPorts"`
	AddressDomains []*string `json:"addressDomains,omitempty" yaml:"addressDomains" bson:"addressDomains"`
	Ipv4Addresses []*string `json:"ipv4Addresses,omitempty" yaml:"ipv4Addresses" bson:"ipv4Addresses"`
	Ipv6Prefixes []*string `json:"ipv6Prefixes,omitempty" yaml:"ipv6Prefixes" bson:"ipv6Prefixes"`
	Ipv4AddrRanges []*Ipv4AddressRange `json:"ipv4AddrRanges,omitempty" yaml:"ipv4AddrRanges" bson:"ipv4AddrRanges"`
	Ipv6PrefixRanges []*Ipv6PrefixRange `json:"ipv6PrefixRanges,omitempty" yaml:"ipv6PrefixRanges" bson:"ipv6PrefixRanges"`
	ServedNfSetIdList []*string `json:"servedNfSetIdList,omitempty" yaml:"servedNfSetIdList" bson:"servedNfSetIdList"`
	RemotePlmnList []*PlmnId `json:"remotePlmnList,omitempty" yaml:"remotePlmnList" bson:"remotePlmnList"`
	RemoteSnpnList []*PlmnIdNid `json:"remoteSnpnList,omitempty" yaml:"remoteSnpnList" bson:"remoteSnpnList"`
	IpReachability IpReachability `json:"ipReachability,omitempty" yaml:"ipReachability" bson:"ipReachability"`
	ScpCapabilities []*ScpCapability `json:"scpCapabilities,omitempty" yaml:"scpCapabilities" bson:"scpCapabilities"`
}
