/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service
 *
 * Source file: 3GPP TS 29.510 V15.3.0; 5G System; Network Function Repository Services; Stage 3
 * Url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



type ChfServiceInfo struct {
	PrimaryChfServiceInstance string `json:"primaryChfServiceInstance,omitempty" yaml:"primaryChfServiceInstance" bson:"primaryChfServiceInstance"`
	SecondaryChfServiceInstance string `json:"secondaryChfServiceInstance,omitempty" yaml:"secondaryChfServiceInstance" bson:"secondaryChfServiceInstance"`
}
