/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V18.4.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// A ConditionItem consists of a number of attributes representing individual conditions (e.g. a SUPI range, or a TAI list). If several attributes/conditions are present, the evaluation of the ConditionItem is <true> if all attributes/conditions are evaluated as <true> (i.e., it follows the AND logical relationship). 
type ConditionItem struct {
	ConsumerNfTypes []*NfType `json:"consumerNfTypes,omitempty" yaml:"consumerNfTypes" bson:"consumerNfTypes"`
	ServiceFeature int32 `json:"serviceFeature,omitempty" yaml:"serviceFeature" bson:"serviceFeature"`
	VsServiceFeature int32 `json:"vsServiceFeature,omitempty" yaml:"vsServiceFeature" bson:"vsServiceFeature"`
	SupiRangeList []*SupiRange `json:"supiRangeList,omitempty" yaml:"supiRangeList" bson:"supiRangeList"`
	GpsiRangeList []*IdentityRange `json:"gpsiRangeList,omitempty" yaml:"gpsiRangeList" bson:"gpsiRangeList"`
	ImpuRangeList []*IdentityRange `json:"impuRangeList,omitempty" yaml:"impuRangeList" bson:"impuRangeList"`
	ImpiRangeList []*IdentityRange `json:"impiRangeList,omitempty" yaml:"impiRangeList" bson:"impiRangeList"`
	PeiList []*string `json:"peiList,omitempty" yaml:"peiList" bson:"peiList"`
	TaiRangeList []*TaiRange `json:"taiRangeList,omitempty" yaml:"taiRangeList" bson:"taiRangeList"`
	DnnList []*string `json:"dnnList,omitempty" yaml:"dnnList" bson:"dnnList"`
}
