/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Data sent in notifications from NRF to subscribed NF Instances
type NotificationData struct {
	Event NotificationEventType `json:"event" yaml:"event" bson:"event"`
	// String providing an URI formatted according to RFC 3986.
	NfInstanceUri string `json:"nfInstanceUri" yaml:"nfInstanceUri" bson:"nfInstanceUri"`
	NfProfile *NfProfileNotificationData `json:"nfProfile,omitempty" yaml:"nfProfile" bson:"nfProfile"`
	ProfileChanges []*ChangeItem `json:"profileChanges,omitempty" yaml:"profileChanges" bson:"profileChanges"`
	ConditionEvent ConditionEventType `json:"conditionEvent,omitempty" yaml:"conditionEvent" bson:"conditionEvent"`
	SubscriptionContext *SubscriptionContext `json:"subscriptionContext,omitempty" yaml:"subscriptionContext" bson:"subscriptionContext"`
}
