/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Oauth2.0 required indication for a given PLMN ID
type PlmnOauth2 struct {
	Oauth2RequiredPlmnIdList []*PlmnId `json:"oauth2RequiredPlmnIdList,omitempty" yaml:"oauth2RequiredPlmnIdList" bson:"oauth2RequiredPlmnIdList"`
	Oauth2NotRequiredPlmnIdList []*PlmnId `json:"oauth2NotRequiredPlmnIdList,omitempty" yaml:"oauth2NotRequiredPlmnIdList" bson:"oauth2NotRequiredPlmnIdList"`
}
