/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models
import (
	"time"
)



// Information of a given NF Service Instance; it is part of the NFProfile of an NF Instance 
type NfService struct {
	ServiceInstanceId string `json:"serviceInstanceId" yaml:"serviceInstanceId" bson:"serviceInstanceId"`
	ServiceName ServiceName `json:"serviceName" yaml:"serviceName" bson:"serviceName"`
	Versions []*NfServiceVersion `json:"versions" yaml:"versions" bson:"versions"`
	Scheme UriScheme `json:"scheme" yaml:"scheme" bson:"scheme"`
	NfServiceStatus NfServiceStatus `json:"nfServiceStatus" yaml:"nfServiceStatus" bson:"nfServiceStatus"`
	// Fully Qualified Domain Name
	Fqdn string `json:"fqdn,omitempty" yaml:"fqdn" bson:"fqdn"`
	// Fully Qualified Domain Name
	InterPlmnFqdn string `json:"interPlmnFqdn,omitempty" yaml:"interPlmnFqdn" bson:"interPlmnFqdn"`
	IpEndPoints []*IpEndPoint `json:"ipEndPoints,omitempty" yaml:"ipEndPoints" bson:"ipEndPoints"`
	ApiPrefix string `json:"apiPrefix,omitempty" yaml:"apiPrefix" bson:"apiPrefix"`
	DefaultNotificationSubscriptions []*DefaultNotificationSubscription `json:"defaultNotificationSubscriptions,omitempty" yaml:"defaultNotificationSubscriptions" bson:"defaultNotificationSubscriptions"`
	AllowedPlmns []*PlmnId `json:"allowedPlmns,omitempty" yaml:"allowedPlmns" bson:"allowedPlmns"`
	AllowedSnpns []*PlmnIdNid `json:"allowedSnpns,omitempty" yaml:"allowedSnpns" bson:"allowedSnpns"`
	AllowedNfTypes []*NfType `json:"allowedNfTypes,omitempty" yaml:"allowedNfTypes" bson:"allowedNfTypes"`
	AllowedNfDomains []*string `json:"allowedNfDomains,omitempty" yaml:"allowedNfDomains" bson:"allowedNfDomains"`
	AllowedNssais []*ExtSnssai `json:"allowedNssais,omitempty" yaml:"allowedNssais" bson:"allowedNssais"`
	// A map (list of key-value pairs) where NF Type serves as key
	AllowedOperationsPerNfType map[string]*[]*string `json:"allowedOperationsPerNfType,omitempty" yaml:"allowedOperationsPerNfType" bson:"allowedOperationsPerNfType"`
	// A map (list of key-value pairs) where NF Instance Id serves as key
	AllowedOperationsPerNfInstance map[string]*[]*string `json:"allowedOperationsPerNfInstance,omitempty" yaml:"allowedOperationsPerNfInstance" bson:"allowedOperationsPerNfInstance"`
	Priority int32 `json:"priority,omitempty" yaml:"priority" bson:"priority"`
	Capacity int32 `json:"capacity,omitempty" yaml:"capacity" bson:"capacity"`
	Load int32 `json:"load,omitempty" yaml:"load" bson:"load"`
	// string with format 'date-time' as defined in OpenAPI.
	LoadTimeStamp *time.Time `json:"loadTimeStamp,omitempty" yaml:"loadTimeStamp" bson:"loadTimeStamp"`
	// string with format 'date-time' as defined in OpenAPI.
	RecoveryTime *time.Time `json:"recoveryTime,omitempty" yaml:"recoveryTime" bson:"recoveryTime"`
	// A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. 
	SupportedFeatures string `json:"supportedFeatures,omitempty" yaml:"supportedFeatures" bson:"supportedFeatures"`
	NfServiceSetIdList []*string `json:"nfServiceSetIdList,omitempty" yaml:"nfServiceSetIdList" bson:"nfServiceSetIdList"`
	SNssais []*ExtSnssai `json:"sNssais,omitempty" yaml:"sNssais" bson:"sNssais"`
	PerPlmnSnssaiList []*PlmnSnssai `json:"perPlmnSnssaiList,omitempty" yaml:"perPlmnSnssaiList" bson:"perPlmnSnssaiList"`
	// Vendor ID of the NF Service instance (Private Enterprise Number assigned by IANA)
	VendorId string `json:"vendorId,omitempty" yaml:"vendorId" bson:"vendorId"`
	// A map (list of key-value pairs) where IANA-assigned SMI Network Management Private Enterprise Codes serves as key 
	SupportedVendorSpecificFeatures map[string]*[]*VendorSpecificFeature `json:"supportedVendorSpecificFeatures,omitempty" yaml:"supportedVendorSpecificFeatures" bson:"supportedVendorSpecificFeatures"`
	Oauth2Required bool `json:"oauth2Required,omitempty" yaml:"oauth2Required" bson:"oauth2Required"`
	PerPlmnOauth2ReqList *PlmnOauth2 `json:"perPlmnOauth2ReqList,omitempty" yaml:"perPlmnOauth2ReqList" bson:"perPlmnOauth2ReqList"`
}
