/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Information of an UPF NF Instance
type UpfInfo struct {
	SNssaiUpfInfoList []*SnssaiUpfInfoItem `json:"sNssaiUpfInfoList" yaml:"sNssaiUpfInfoList" bson:"sNssaiUpfInfoList"`
	SmfServingArea []*string `json:"smfServingArea,omitempty" yaml:"smfServingArea" bson:"smfServingArea"`
	InterfaceUpfInfoList []*InterfaceUpfInfoItem `json:"interfaceUpfInfoList,omitempty" yaml:"interfaceUpfInfoList" bson:"interfaceUpfInfoList"`
	IwkEpsInd bool `json:"iwkEpsInd,omitempty" yaml:"iwkEpsInd" bson:"iwkEpsInd"`
	PduSessionTypes []*PduSessionType `json:"pduSessionTypes,omitempty" yaml:"pduSessionTypes" bson:"pduSessionTypes"`
	AtsssCapability *AtsssCapability `json:"atsssCapability,omitempty" yaml:"atsssCapability" bson:"atsssCapability"`
	UeIpAddrInd bool `json:"ueIpAddrInd,omitempty" yaml:"ueIpAddrInd" bson:"ueIpAddrInd"`
	TaiList []*Tai `json:"taiList,omitempty" yaml:"taiList" bson:"taiList"`
	TaiRangeList []*TaiRange `json:"taiRangeList,omitempty" yaml:"taiRangeList" bson:"taiRangeList"`
	WAgfInfo *WAgfInfo `json:"wAgfInfo,omitempty" yaml:"wAgfInfo" bson:"wAgfInfo"`
	TngfInfo *TngfInfo `json:"tngfInfo,omitempty" yaml:"tngfInfo" bson:"tngfInfo"`
	TwifInfo *TwifInfo `json:"twifInfo,omitempty" yaml:"twifInfo" bson:"twifInfo"`
	Priority int32 `json:"priority,omitempty" yaml:"priority" bson:"priority"`
	RedundantGtpu bool `json:"redundantGtpu,omitempty" yaml:"redundantGtpu" bson:"redundantGtpu"`
	Ipups bool `json:"ipups,omitempty" yaml:"ipups" bson:"ipups"`
	DataForwarding bool `json:"dataForwarding,omitempty" yaml:"dataForwarding" bson:"dataForwarding"`
	SupportedPfcpFeatures string `json:"supportedPfcpFeatures,omitempty" yaml:"supportedPfcpFeatures" bson:"supportedPfcpFeatures"`
}
