/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Information of a SEPP Instance
type SeppInfo struct {
	SeppPrefix string `json:"seppPrefix,omitempty" yaml:"seppPrefix" bson:"seppPrefix"`
	// Port numbers for HTTP and HTTPS. The key of the map shall be \"http\" or \"https\". 
	SeppPorts map[string]*int32 `json:"seppPorts,omitempty" yaml:"seppPorts" bson:"seppPorts"`
	RemotePlmnList []*PlmnId `json:"remotePlmnList,omitempty" yaml:"remotePlmnList" bson:"remotePlmnList"`
	RemoteSnpnList []*PlmnIdNid `json:"remoteSnpnList,omitempty" yaml:"remoteSnpnList" bson:"remoteSnpnList"`
}
