/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models


type RatType string

// List of RatType
const (
        RatType_NR RatType = "NR"
        RatType_EUTRA RatType = "EUTRA"
        RatType_WLAN RatType = "WLAN"
        RatType_VIRTUAL RatType = "VIRTUAL"
        RatType_NBIOT RatType = "NBIOT"
        RatType_WIRELINE RatType = "WIRELINE"
        RatType_WIRELINE_CABLE RatType = "WIRELINE_CABLE"
        RatType_WIRELINE_BBF RatType = "WIRELINE_BBF"
        RatType_LTE_M RatType = "LTE-M"
        RatType_NR_U RatType = "NR_U"
        RatType_EUTRA_U RatType = "EUTRA_U"
        RatType_TRUSTED_N3_GA RatType = "TRUSTED_N3GA"
        RatType_TRUSTED_WLAN RatType = "TRUSTED_WLAN"
        RatType_UTRA RatType = "UTRA"
        RatType_GERA RatType = "GERA"
        RatType_NR_LEO RatType = "NR_LEO"
        RatType_NR_MEO RatType = "NR_MEO"
        RatType_NR_GEO RatType = "NR_GEO"
        RatType_NR_OTHER_SAT RatType = "NR_OTHER_SAT"
        RatType_NR_REDCAP RatType = "NR_REDCAP"
)


