/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Subscription to a set of NF Instances (NEFs), identified by Event ID(s) provided by AF, S-NSSAI(s), AF Instance ID, Application Identifier, External Identifier, External Group Identifier, or domain name. 
type NefCond struct {
	ConditionType string `json:"conditionType" yaml:"conditionType" bson:"conditionType"`
	AfEvents []*AfEvent `json:"afEvents,omitempty" yaml:"afEvents" bson:"afEvents"`
	SnssaiList []*Snssai `json:"snssaiList,omitempty" yaml:"snssaiList" bson:"snssaiList"`
	PfdData *PfdData `json:"pfdData,omitempty" yaml:"pfdData" bson:"pfdData"`
	GpsiRanges []*IdentityRange `json:"gpsiRanges,omitempty" yaml:"gpsiRanges" bson:"gpsiRanges"`
	ExternalGroupIdentifiersRanges []*IdentityRange `json:"externalGroupIdentifiersRanges,omitempty" yaml:"externalGroupIdentifiersRanges" bson:"externalGroupIdentifiersRanges"`
	ServedFqdnList []*string `json:"servedFqdnList,omitempty" yaml:"servedFqdnList" bson:"servedFqdnList"`
}
