/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Information of an MB-SMF NF Instance
type MbSmfInfo struct {
	// A map (list of key-value pairs) where a valid JSON string serves as key
	SNssaiInfoList map[string]*SnssaiMbSmfInfoItem `json:"sNssaiInfoList,omitempty" yaml:"sNssaiInfoList" bson:"sNssaiInfoList"`
	// A map (list of key-value pairs) where a valid JSON string serves as key
	TmgiRangeList map[string]*TmgiRange `json:"tmgiRangeList,omitempty" yaml:"tmgiRangeList" bson:"tmgiRangeList"`
	TaiList []*Tai `json:"taiList,omitempty" yaml:"taiList" bson:"taiList"`
	TaiRangeList []*TaiRange `json:"taiRangeList,omitempty" yaml:"taiRangeList" bson:"taiRangeList"`
	// A map (list of key-value pairs) where a valid JSON string serves as key
	MbsSessionList map[string]*MbsSession `json:"mbsSessionList,omitempty" yaml:"mbsSessionList" bson:"mbsSessionList"`
}
