/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Information of an MB-UPF NF Instance
type MbUpfInfo struct {
	SNssaiMbUpfInfoList []*SnssaiUpfInfoItem `json:"sNssaiMbUpfInfoList" yaml:"sNssaiMbUpfInfoList" bson:"sNssaiMbUpfInfoList"`
	MbSmfServingArea []*string `json:"mbSmfServingArea,omitempty" yaml:"mbSmfServingArea" bson:"mbSmfServingArea"`
	InterfaceMbUpfInfoList []*InterfaceUpfInfoItem `json:"interfaceMbUpfInfoList,omitempty" yaml:"interfaceMbUpfInfoList" bson:"interfaceMbUpfInfoList"`
	TaiList []*Tai `json:"taiList,omitempty" yaml:"taiList" bson:"taiList"`
	TaiRangeList []*TaiRange `json:"taiRangeList,omitempty" yaml:"taiRangeList" bson:"taiRangeList"`
	Priority int32 `json:"priority,omitempty" yaml:"priority" bson:"priority"`
	SupportedPfcpFeatures string `json:"supportedPfcpFeatures,omitempty" yaml:"supportedPfcpFeatures" bson:"supportedPfcpFeatures"`
}
