/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models


type UpInterfaceType string

// List of UPInterfaceType
const (
        UpInterfaceType_N3 UpInterfaceType = "N3"
        UpInterfaceType_N6 UpInterfaceType = "N6"
        UpInterfaceType_N9 UpInterfaceType = "N9"
        UpInterfaceType_DATA_FORWARDING UpInterfaceType = "DATA_FORWARDING"
        UpInterfaceType_N3_MB UpInterfaceType = "N3MB"
        UpInterfaceType_N6_MB UpInterfaceType = "N6MB"
        UpInterfaceType_N19_MB UpInterfaceType = "N19MB"
        UpInterfaceType_NMB9 UpInterfaceType = "NMB9"
)


