/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Condition to determine the set of NFs to monitor under a certain subscription in NRF 
type SubscrCond struct {
	// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  
	NfInstanceId string `json:"nfInstanceId" yaml:"nfInstanceId" bson:"nfInstanceId"`
	NfInstanceIdList []*string `json:"nfInstanceIdList" yaml:"nfInstanceIdList" bson:"nfInstanceIdList"`
	NfType string `json:"nfType" yaml:"nfType" bson:"nfType"`
	ServiceName ServiceName `json:"serviceName" yaml:"serviceName" bson:"serviceName"`
	ConditionType string `json:"conditionType" yaml:"conditionType" bson:"conditionType"`
	ServiceNameList []*ServiceName `json:"serviceNameList" yaml:"serviceNameList" bson:"serviceNameList"`
	// String identifying the AMF Set ID (10 bits) as specified in clause 2.10.1 of 3GPP TS 23.003.  It is encoded as a string of 3 hexadecimal characters where the first character is limited to  values 0 to 3 (i.e. 10 bits). 
	AmfSetId string `json:"amfSetId,omitempty" yaml:"amfSetId" bson:"amfSetId"`
	// String identifying the AMF Set ID (10 bits) as specified in clause 2.10.1 of 3GPP TS 23.003.  It is encoded as a string of 3 hexadecimal characters where the first character is limited to  values 0 to 3 (i.e. 10 bits) 
	AmfRegionId string `json:"amfRegionId,omitempty" yaml:"amfRegionId" bson:"amfRegionId"`
	GuamiList []*Guami `json:"guamiList" yaml:"guamiList" bson:"guamiList"`
	SnssaiList []*Snssai `json:"snssaiList" yaml:"snssaiList" bson:"snssaiList"`
	NsiList []*string `json:"nsiList,omitempty" yaml:"nsiList" bson:"nsiList"`
	// Identifier of a group of NFs.
	NfGroupId string `json:"nfGroupId" yaml:"nfGroupId" bson:"nfGroupId"`
	NfGroupIdList []*string `json:"nfGroupIdList" yaml:"nfGroupIdList" bson:"nfGroupIdList"`
	// NF Set Identifier (see clause 28.12 of 3GPP TS 23.003), formatted as the following string \"set<Set ID>.<nftype>set.5gc.mnc<MNC>.mcc<MCC>\", or  \"set<SetID>.<NFType>set.5gc.nid<NID>.mnc<MNC>.mcc<MCC>\" with  <MCC> encoded as defined in clause 5.4.2 (\"Mcc\" data type definition)  <MNC> encoding the Mobile Network Code part of the PLMN, comprising 3 digits.    If there are only 2 significant digits in the MNC, one \"0\" digit shall be inserted    at the left side to fill the 3 digits coding of MNC.  Pattern: '^[0-9]{3}$' <NFType> encoded as a value defined in Table 6.1.6.3.3-1 of 3GPP TS 29.510 but    with lower case characters <Set ID> encoded as a string of characters consisting of    alphabetic characters (A-Z and a-z), digits (0-9) and/or the hyphen (-) and that    shall end with either an alphabetic character or a digit.  
	NfSetId string `json:"nfSetId" yaml:"nfSetId" bson:"nfSetId"`
	// NF Service Set Identifier (see clause 28.12 of 3GPP TS 23.003) formatted as the following  string \"set<Set ID>.sn<Service Name>.nfi<NF Instance ID>.5gc.mnc<MNC>.mcc<MCC>\", or  \"set<SetID>.sn<ServiceName>.nfi<NFInstanceID>.5gc.nid<NID>.mnc<MNC>.mcc<MCC>\" with  <MCC> encoded as defined in clause 5.4.2 (\"Mcc\" data type definition)   <MNC> encoding the Mobile Network Code part of the PLMN, comprising 3 digits.    If there are only 2 significant digits in the MNC, one \"0\" digit shall be inserted    at the left side to fill the 3 digits coding of MNC.  Pattern: '^[0-9]{3}$' <NID> encoded as defined in clause 5.4.2 (\"Nid\" data type definition)  <NFInstanceId> encoded as defined in clause 5.3.2  <ServiceName> encoded as defined in 3GPP TS 29.510  <Set ID> encoded as a string of characters consisting of alphabetic    characters (A-Z and a-z), digits (0-9) and/or the hyphen (-) and that shall end    with either an alphabetic character or a digit. 
	NfServiceSetId string `json:"nfServiceSetId" yaml:"nfServiceSetId" bson:"nfServiceSetId"`
	SmfServingArea []*string `json:"smfServingArea,omitempty" yaml:"smfServingArea" bson:"smfServingArea"`
	TaiList []*Tai `json:"taiList,omitempty" yaml:"taiList" bson:"taiList"`
	ScpDomains []*string `json:"scpDomains" yaml:"scpDomains" bson:"scpDomains"`
	NfTypeList []*NfType `json:"nfTypeList,omitempty" yaml:"nfTypeList" bson:"nfTypeList"`
	AnalyticsIds []*string `json:"analyticsIds,omitempty" yaml:"analyticsIds" bson:"analyticsIds"`
	TaiRangeList []*TaiRange `json:"taiRangeList,omitempty" yaml:"taiRangeList" bson:"taiRangeList"`
	ServingNfTypeList []*NfType `json:"servingNfTypeList,omitempty" yaml:"servingNfTypeList" bson:"servingNfTypeList"`
	ServingNfSetIdList []*string `json:"servingNfSetIdList,omitempty" yaml:"servingNfSetIdList" bson:"servingNfSetIdList"`
	MlAnalyticsList []*MlAnalyticsInfo `json:"mlAnalyticsList,omitempty" yaml:"mlAnalyticsList" bson:"mlAnalyticsList"`
	AfEvents []*AfEvent `json:"afEvents,omitempty" yaml:"afEvents" bson:"afEvents"`
	PfdData *PfdData `json:"pfdData,omitempty" yaml:"pfdData" bson:"pfdData"`
	GpsiRanges []*IdentityRange `json:"gpsiRanges,omitempty" yaml:"gpsiRanges" bson:"gpsiRanges"`
	ExternalGroupIdentifiersRanges []*IdentityRange `json:"externalGroupIdentifiersRanges,omitempty" yaml:"externalGroupIdentifiersRanges" bson:"externalGroupIdentifiersRanges"`
	ServedFqdnList []*string `json:"servedFqdnList,omitempty" yaml:"servedFqdnList" bson:"servedFqdnList"`
}
