/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Information of an EASDF NF Instance
type EasdfInfo struct {
	SNssaiEasdfInfoList []*SnssaiEasdfInfoItem `json:"sNssaiEasdfInfoList,omitempty" yaml:"sNssaiEasdfInfoList" bson:"sNssaiEasdfInfoList"`
	EasdfN6IpAddressList []*IpAddr `json:"easdfN6IpAddressList,omitempty" yaml:"easdfN6IpAddressList" bson:"easdfN6IpAddressList"`
	UpfN6IpAddressList []*IpAddr `json:"upfN6IpAddressList,omitempty" yaml:"upfN6IpAddressList" bson:"upfN6IpAddressList"`
}
