/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Information of a BSF NF Instance
type BsfInfo struct {
	DnnList []*string `json:"dnnList,omitempty" yaml:"dnnList" bson:"dnnList"`
	IpDomainList []*string `json:"ipDomainList,omitempty" yaml:"ipDomainList" bson:"ipDomainList"`
	Ipv4AddressRanges []*Ipv4AddressRange `json:"ipv4AddressRanges,omitempty" yaml:"ipv4AddressRanges" bson:"ipv4AddressRanges"`
	Ipv6PrefixRanges []*Ipv6PrefixRange `json:"ipv6PrefixRanges,omitempty" yaml:"ipv6PrefixRanges" bson:"ipv6PrefixRanges"`
	// Fully Qualified Domain Name
	RxDiamHost string `json:"rxDiamHost,omitempty" yaml:"rxDiamHost" bson:"rxDiamHost"`
	// Fully Qualified Domain Name
	RxDiamRealm string `json:"rxDiamRealm,omitempty" yaml:"rxDiamRealm" bson:"rxDiamRealm"`
	// Identifier of a group of NFs.
	GroupId string `json:"groupId,omitempty" yaml:"groupId" bson:"groupId"`
	SupiRanges []*SupiRange `json:"supiRanges,omitempty" yaml:"supiRanges" bson:"supiRanges"`
	GpsiRanges []*IdentityRange `json:"gpsiRanges,omitempty" yaml:"gpsiRanges" bson:"gpsiRanges"`
}
