/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Indicate the supported ProSe Capability by the PCF.
type ProSeCapability struct {
	ProseDirectDiscovey bool `json:"proseDirectDiscovey,omitempty" yaml:"proseDirectDiscovey" bson:"proseDirectDiscovey"`
	ProseDirectCommunication bool `json:"proseDirectCommunication,omitempty" yaml:"proseDirectCommunication" bson:"proseDirectCommunication"`
	ProseL2UetoNetworkRelay bool `json:"proseL2UetoNetworkRelay,omitempty" yaml:"proseL2UetoNetworkRelay" bson:"proseL2UetoNetworkRelay"`
	ProseL3UetoNetworkRelay bool `json:"proseL3UetoNetworkRelay,omitempty" yaml:"proseL3UetoNetworkRelay" bson:"proseL3UetoNetworkRelay"`
	ProseL2RemoteUe bool `json:"proseL2RemoteUe,omitempty" yaml:"proseL2RemoteUe" bson:"proseL2RemoteUe"`
	ProseL3RemoteUe bool `json:"proseL3RemoteUe,omitempty" yaml:"proseL3RemoteUe" bson:"proseL3RemoteUe"`
}
