/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models


type NwdafEvent string

// List of NwdafEvent
const (
        NwdafEvent_SLICE_LOAD_LEVEL NwdafEvent = "SLICE_LOAD_LEVEL"
        NwdafEvent_NETWORK_PERFORMANCE NwdafEvent = "NETWORK_PERFORMANCE"
        NwdafEvent_NF_LOAD NwdafEvent = "NF_LOAD"
        NwdafEvent_SERVICE_EXPERIENCE NwdafEvent = "SERVICE_EXPERIENCE"
        NwdafEvent_UE_MOBILITY NwdafEvent = "UE_MOBILITY"
        NwdafEvent_UE_COMMUNICATION NwdafEvent = "UE_COMMUNICATION"
        NwdafEvent_QOS_SUSTAINABILITY NwdafEvent = "QOS_SUSTAINABILITY"
        NwdafEvent_ABNORMAL_BEHAVIOUR NwdafEvent = "ABNORMAL_BEHAVIOUR"
        NwdafEvent_USER_DATA_CONGESTION NwdafEvent = "USER_DATA_CONGESTION"
        NwdafEvent_NSI_LOAD_LEVEL NwdafEvent = "NSI_LOAD_LEVEL"
        NwdafEvent_DN_PERFORMANCE NwdafEvent = "DN_PERFORMANCE"
        NwdafEvent_DISPERSION NwdafEvent = "DISPERSION"
        NwdafEvent_RED_TRANS_EXP NwdafEvent = "RED_TRANS_EXP"
        NwdafEvent_WLAN_PERFORMANCE NwdafEvent = "WLAN_PERFORMANCE"
        NwdafEvent_SM_CONGESTION NwdafEvent = "SM_CONGESTION"
)


