/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models


type NotificationType string

// List of NotificationType
const (
        NotificationType_N1_MESSAGES NotificationType = "N1_MESSAGES"
        NotificationType_N2_INFORMATION NotificationType = "N2_INFORMATION"
        NotificationType_LOCATION_NOTIFICATION NotificationType = "LOCATION_NOTIFICATION"
        NotificationType_DATA_REMOVAL_NOTIFICATION NotificationType = "DATA_REMOVAL_NOTIFICATION"
        NotificationType_DATA_CHANGE_NOTIFICATION NotificationType = "DATA_CHANGE_NOTIFICATION"
        NotificationType_LOCATION_UPDATE_NOTIFICATION NotificationType = "LOCATION_UPDATE_NOTIFICATION"
        NotificationType_NSSAA_REAUTH_NOTIFICATION NotificationType = "NSSAA_REAUTH_NOTIFICATION"
        NotificationType_NSSAA_REVOC_NOTIFICATION NotificationType = "NSSAA_REVOC_NOTIFICATION"
        NotificationType_MATCH_INFO_NOTIFICATION NotificationType = "MATCH_INFO_NOTIFICATION"
        NotificationType_DATA_RESTORATION_NOTIFICATION NotificationType = "DATA_RESTORATION_NOTIFICATION"
        NotificationType_TSCTS_NOTIFICATION NotificationType = "TSCTS_NOTIFICATION"
        NotificationType_LCS_KEY_DELIVERY_NOTIFICATION NotificationType = "LCS_KEY_DELIVERY_NOTIFICATION"
        NotificationType_UUAA_MM_AUTH_NOTIFICATION NotificationType = "UUAA_MM_AUTH_NOTIFICATION"
)


