/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// MBS Service Area Information for location dependent MBS session
type MbsServiceAreaInfo struct {
	// Integer where the allowed values correspond to the value range of an unsigned 16-bit integer.
	AreaSessionId int32 `json:"areaSessionId" yaml:"areaSessionId" bson:"areaSessionId"`
	MbsServiceArea *MbsServiceArea `json:"mbsServiceArea" yaml:"mbsServiceArea" bson:"mbsServiceArea"`
}
