/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V18.4.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.3.0-alpha.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models


type EventType string

// List of EventType
const (
        EventType_QOS_MONITORING EventType = "QOS_MONITORING"
        EventType_USER_DATA_USAGE_MEASURES EventType = "USER_DATA_USAGE_MEASURES"
        EventType_USER_DATA_USAGE_TRENDS EventType = "USER_DATA_USAGE_TRENDS"
        EventType_TSC_MNGT_INFO EventType = "TSC_MNGT_INFO"
)


