/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// SCP Domain specific information
type ScpDomainInfo struct {
	// Fully Qualified Domain Name
	ScpFqdn string `json:"scpFqdn,omitempty" yaml:"scpFqdn" bson:"scpFqdn"`
	ScpIpEndPoints []*IpEndPoint `json:"scpIpEndPoints,omitempty" yaml:"scpIpEndPoints" bson:"scpIpEndPoints"`
	ScpPrefix string `json:"scpPrefix,omitempty" yaml:"scpPrefix" bson:"scpPrefix"`
	// Port numbers for HTTP and HTTPS. The key of the map shall be \"http\" or \"https\". 
	ScpPorts map[string]*int32 `json:"scpPorts,omitempty" yaml:"scpPorts" bson:"scpPorts"`
}
