/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Information of a PCF NF Instance
type PcfInfo struct {
	// Identifier of a group of NFs.
	GroupId string `json:"groupId,omitempty" yaml:"groupId" bson:"groupId"`
	DnnList []*string `json:"dnnList,omitempty" yaml:"dnnList" bson:"dnnList"`
	SupiRanges []*SupiRange `json:"supiRanges,omitempty" yaml:"supiRanges" bson:"supiRanges"`
	GpsiRanges []*IdentityRange `json:"gpsiRanges,omitempty" yaml:"gpsiRanges" bson:"gpsiRanges"`
	// Fully Qualified Domain Name
	RxDiamHost string `json:"rxDiamHost,omitempty" yaml:"rxDiamHost" bson:"rxDiamHost"`
	// Fully Qualified Domain Name
	RxDiamRealm string `json:"rxDiamRealm,omitempty" yaml:"rxDiamRealm" bson:"rxDiamRealm"`
	V2xSupportInd bool `json:"v2xSupportInd,omitempty" yaml:"v2xSupportInd" bson:"v2xSupportInd"`
	ProseSupportInd bool `json:"proseSupportInd,omitempty" yaml:"proseSupportInd" bson:"proseSupportInd"`
	ProseCapability *ProSeCapability `json:"proseCapability,omitempty" yaml:"proseCapability" bson:"proseCapability"`
	V2xCapability *V2xCapability `json:"v2xCapability,omitempty" yaml:"v2xCapability" bson:"v2xCapability"`
}
