/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// It contains data which need to be changed.
type ChangeItem struct {
	Op ChangeType `json:"op" yaml:"op" bson:"op"`
	// contains a JSON pointer value (as defined in IETF RFC 6901) that references a target  location within the resource on which the change has been applied. 
	Path string `json:"path" yaml:"path" bson:"path"`
	// indicates the path of the source JSON element (according to JSON Pointer syntax)  being moved or copied to the location indicated by the \"path\" attribute. It shall  be present if the \"op\" attribute is of value \"MOVE\". 
	From string `json:"from,omitempty" yaml:"from" bson:"from"`
	OrigValue map[string]interface{} `json:"origValue,omitempty" yaml:"origValue" bson:"origValue"`
	NewValue map[string]interface{} `json:"newValue,omitempty" yaml:"newValue" bson:"newValue"`
}
