/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// IP addressing information of a given NFService; it consists on, e.g. IP address, TCP port, transport protocol... 
type IpEndPoint struct {
	// String identifying a IPv4 address formatted in the 'dotted decimal' notation as defined in RFC 1166. 
	Ipv4Address string `json:"ipv4Address,omitempty" yaml:"ipv4Address" bson:"ipv4Address"`
	Ipv6Address string `json:"ipv6Address,omitempty" yaml:"ipv6Address" bson:"ipv6Address"`
	Transport TransportProtocol `json:"transport,omitempty" yaml:"transport" bson:"transport"`
	Port int32 `json:"port,omitempty" yaml:"port" bson:"port"`
}
