/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type AfEvent string

// List of AfEvent
const (
	AfEvent_SVC_EXPERIENCE           AfEvent = "SVC_EXPERIENCE"
	AfEvent_UE_MOBILITY              AfEvent = "UE_MOBILITY"
	AfEvent_UE_COMM                  AfEvent = "UE_COMM"
	AfEvent_EXCEPTIONS               AfEvent = "EXCEPTIONS"
	AfEvent_USER_DATA_CONGESTION     AfEvent = "USER_DATA_CONGESTION"
	AfEvent_PERF_DATA                AfEvent = "PERF_DATA"
	AfEvent_DISPERSION               AfEvent = "DISPERSION"
	AfEvent_COLLECTIVE_BEHAVIOUR     AfEvent = "COLLECTIVE_BEHAVIOUR"
	AfEvent_MS_QOE_METRICS           AfEvent = "MS_QOE_METRICS"
	AfEvent_MS_CONSUMPTION           AfEvent = "MS_CONSUMPTION"
	AfEvent_MS_NET_ASSIST_INVOCATION AfEvent = "MS_NET_ASSIST_INVOCATION"
	AfEvent_MS_DYN_POLICY_INVOCATION AfEvent = "MS_DYN_POLICY_INVOCATION"
	AfEvent_MS_ACCESS_ACTIVITY       AfEvent = "MS_ACCESS_ACTIVITY"
)
