/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Information of a trusted AF Instance
type TrustAfInfo struct {
	SNssaiInfoList []*SnssaiInfoItem `json:"sNssaiInfoList,omitempty" yaml:"sNssaiInfoList" bson:"sNssaiInfoList"`
	AfEvents []*AfEvent `json:"afEvents,omitempty" yaml:"afEvents" bson:"afEvents"`
	AppIds []*string `json:"appIds,omitempty" yaml:"appIds" bson:"appIds"`
	InternalGroupId []*string `json:"internalGroupId,omitempty" yaml:"internalGroupId" bson:"internalGroupId"`
	MappingInd bool `json:"mappingInd,omitempty" yaml:"mappingInd" bson:"mappingInd"`
}
