/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Information of a CHF NF Instance
type ChfInfo struct {
	SupiRangeList []*SupiRange `json:"supiRangeList,omitempty" yaml:"supiRangeList" bson:"supiRangeList"`
	GpsiRangeList []*IdentityRange `json:"gpsiRangeList,omitempty" yaml:"gpsiRangeList" bson:"gpsiRangeList"`
	PlmnRangeList []*PlmnRange `json:"plmnRangeList,omitempty" yaml:"plmnRangeList" bson:"plmnRangeList"`
	// Identifier of a group of NFs.
	GroupId string `json:"groupId,omitempty" yaml:"groupId" bson:"groupId"`
	// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  
	PrimaryChfInstance string `json:"primaryChfInstance,omitempty" yaml:"primaryChfInstance" bson:"primaryChfInstance"`
	// String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.  
	SecondaryChfInstance string `json:"secondaryChfInstance,omitempty" yaml:"secondaryChfInstance" bson:"secondaryChfInstance"`
}
