/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models



// Information of an SMF NF Instance
type SmfInfo struct {
	SNssaiSmfInfoList []*SnssaiSmfInfoItem `json:"sNssaiSmfInfoList" yaml:"sNssaiSmfInfoList" bson:"sNssaiSmfInfoList"`
	TaiList []*Tai `json:"taiList,omitempty" yaml:"taiList" bson:"taiList"`
	TaiRangeList []*TaiRange `json:"taiRangeList,omitempty" yaml:"taiRangeList" bson:"taiRangeList"`
	// Fully Qualified Domain Name
	PgwFqdn string `json:"pgwFqdn,omitempty" yaml:"pgwFqdn" bson:"pgwFqdn"`
	PgwIpAddrList []*IpAddr `json:"pgwIpAddrList,omitempty" yaml:"pgwIpAddrList" bson:"pgwIpAddrList"`
	AccessType []*AccessType `json:"accessType,omitempty" yaml:"accessType" bson:"accessType"`
	Priority int32 `json:"priority,omitempty" yaml:"priority" bson:"priority"`
	VsmfSupportInd bool `json:"vsmfSupportInd,omitempty" yaml:"vsmfSupportInd" bson:"vsmfSupportInd"`
	PgwFqdnList []*string `json:"pgwFqdnList,omitempty" yaml:"pgwFqdnList" bson:"pgwFqdnList"`
	SmfOnboardingCapability bool `json:"smfOnboardingCapability,omitempty" yaml:"smfOnboardingCapability" bson:"smfOnboardingCapability"`
	IsmfSupportInd bool `json:"ismfSupportInd,omitempty" yaml:"ismfSupportInd" bson:"ismfSupportInd"`
	SmfUPRPCapability bool `json:"smfUPRPCapability,omitempty" yaml:"smfUPRPCapability" bson:"smfUPRPCapability"`
}
