/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models


type ExternalClientType string

// List of ExternalClientType
const (
        ExternalClientType_EMERGENCY_SERVICES ExternalClientType = "EMERGENCY_SERVICES"
        ExternalClientType_VALUE_ADDED_SERVICES ExternalClientType = "VALUE_ADDED_SERVICES"
        ExternalClientType_PLMN_OPERATOR_SERVICES ExternalClientType = "PLMN_OPERATOR_SERVICES"
        ExternalClientType_LAWFUL_INTERCEPT_SERVICES ExternalClientType = "LAWFUL_INTERCEPT_SERVICES"
        ExternalClientType_PLMN_OPERATOR_BROADCAST_SERVICES ExternalClientType = "PLMN_OPERATOR_BROADCAST_SERVICES"
        ExternalClientType_PLMN_OPERATOR_OM ExternalClientType = "PLMN_OPERATOR_OM"
        ExternalClientType_PLMN_OPERATOR_ANONYMOUS_STATISTICS ExternalClientType = "PLMN_OPERATOR_ANONYMOUS_STATISTICS"
        ExternalClientType_PLMN_OPERATOR_TARGET_MS_SERVICE_SUPPORT ExternalClientType = "PLMN_OPERATOR_TARGET_MS_SERVICE_SUPPORT"
)


