/*
 * NRF NFManagement Service
 *
 * NRF NFManagement Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * Source file: 3GPP TS 29.510 V17.11.0; 5G System; Network Function Repository Services; Stage 3
 * Url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
 *
 * API version: 1.2.5
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models


type N2InformationClass string

// List of N2InformationClass
const (
        N2InformationClass_SM N2InformationClass = "SM"
        N2InformationClass_NRP_PA N2InformationClass = "NRPPa"
        N2InformationClass_PWS N2InformationClass = "PWS"
        N2InformationClass_PWS_BCAL N2InformationClass = "PWS-BCAL"
        N2InformationClass_PWS_RF N2InformationClass = "PWS-RF"
        N2InformationClass_RAN N2InformationClass = "RAN"
        N2InformationClass_V2_X N2InformationClass = "V2X"
        N2InformationClass_PROSE N2InformationClass = "PROSE"
)


